export {default as pug} from './pug.js';
export {default as scss} from './scss.js';
export {default as fonts} from './fonts.js';
export {default as images} from './images.js';
export {default as svg} from './svg.js';
export {default as clean} from './clean.js';
export {default as serve} from './serve.js';
export {default as reload} from './reload.js';
export {default as watch} from './watch.js';
export {scriptsPages} from './scripts.js';
export {scriptsVendor} from './scripts.js';
